# SQL-Based ETL & Data Cleaning

## Dataset

The loan dataset provides a detailed snapshot of consumer lending, encompassing a wide array of information about individual loans.

1. **id**: A unique identifier for each loan.
2. **year**: The year when the loan was issued.
3. **issue_d**: The specific date when the loan was issued.
4. **final_d**: A date-related field, possibly indicating the final date of the loan term or the date of final payment.
5. **emp_length_int**: Employment length of the borrower, in years, as an integer.
6. **home_ownership**: The housing status of the borrower, indicating whether they own a home, rent, or have another arrangement.
7. **home_ownership_cat**: Categorical encoding of the home ownership status.
8. **income_category**: A categorical representation of the borrower's income level.
9. **annual_inc**: The annual income of the borrower.
10. **income_cat**: A categorical encoding of the borrower's income.
11. **loan_amount**: The amount of money borrowed.
12. **term**: The term of the loan, typically in months or years.
13. **term_cat**: Categorical encoding of the loan term.
14. **application_type**: Indicates whether the loan application was individual or joint.
15. **application_type_cat**: Categorical encoding of the application type.
16. **purpose**: The purpose of the loan (e.g., debt consolidation, home improvement).
17. **purpose_cat**: Categorical encoding of the loan purpose.
18. **interest_payments**: A descriptor of the interest payments (e.g., high, low).
19. **interest_payment_cat**: Categorical encoding of the interest payments.
20. **loan_condition**: Status of the loan (Good Loan and Bad Loan).
21. **loan_condition_cat**: Categorical encoding of the loan condition.
22. **interest_rate**: The interest rate on the loan.
23. **grade**: The loan grade, which is typically an assessment of the loan's risk.
24. **grade_cat**: Categorical encoding of the loan grade.
25. **dti**: The debt-to-income ratio of the borrower.
26. **total_pymnt**: The total payments made on the loan to date.
27. **total_rec_prncp**: The total principal received to date.
28. **recoveries**: The amount recovered on the loan after default.
29. **installment**: The monthly payment owed by the borrower.
30. **region**: The geographical region of the borrower.

## A. Extract Phase (Data Loading & Verification)

1. **Create a table named `loans`** with appropriate data types for all columns listed in the dataset (`loan_final313_.csv`).
    
    *Use SQL `CREATE TABLE` syntax ensuring numeric, date, and categorical fields are properly defined.*

Loading the Dataset.

In [1]:
from google.colab import files
uploaded = files.upload()

Saving loan_final313_.csv to loan_final313_.csv

In [45]:
import sqlite3

conn = sqlite3.connect('loans.db')
cursor = conn.cursor()

cursor.execute("""
DROP TABLE IF EXISTS loans;
""")

cursor.execute("""
CREATE TABLE loans (
    id INTEGER,
    year INTEGER,
    issue_d TEXT,
    final_d TEXT,
    emp_length_int REAL,
    home_ownership TEXT,
    home_ownership_cat INTEGER,
    income_category TEXT,
    annual_inc REAL,
    income_cat INTEGER,
    loan_amount REAL,
    term TEXT,
    term_cat INTEGER,
    application_type TEXT,
    application_type_cat INTEGER,
    purpose TEXT,
    purpose_cat INTEGER,
    interest_payments TEXT,
    interest_payment_cat INTEGER,
    loan_condition TEXT,
    loan_condition_cat INTEGER,
    interest_rate REAL,
    grade TEXT,
    grade_cat INTEGER,
    dti REAL,
    total_pymnt REAL,
    total_rec_prncp REAL,
    recoveries REAL,
    installment REAL,
    region TEXT
);
""")

conn.commit()

2. **Import the `loan_final313_.csv` file** into your SQL environment (e.g., MySQL, PostgreSQL, SQL Server).
    
    *Validate that all rows and columns are loaded successfully.*

In [46]:
import pandas as pd

df = pd.read_csv('loan_final313_.csv')

df.to_sql('loans', conn, if_exists='append', index=False)

70000

3. Display the first 10 records from the table to confirm successful loading.

In [47]:
pd.read_sql("SELECT * FROM loans LIMIT 10;", conn)

,id,year,issue_d,final_d,emp_length_int,home_ownership,home_ownership_cat,income_category,annual_inc,income_cat,...,loan_condition_cat,interest_rate,grade,grade_cat,dti,total_pymnt,total_rec_prncp,recoveries,installment,region
0,6297794,2013,01/07/2013,1122015,10.0,MORTGAGE,3,Low,55000.0,1,...,0,10.64,B,2,20.57,11630.35000,10000.00,0.0,325.69,cannught
1,4526163,2013,01/05/2013,1102014,9.0,RENT,1,Low,60000.0,1,...,0,21.00,E,5,8.82,13165.83707,10575.00,0.0,398.42,cannught
2,9001808,2013,01/11/2013,1012016,10.0,MORTGAGE,3,Low,63000.0,1,...,0,13.67,B,2,8.72,7849.66000,6033.91,0.0,301.91,munster
3,7306367,2013,01/09/2013,1122015,10.0,MORTGAGE,3,Low,100000.0,1,...,0,16.20,C,3,19.52,6924.42000,3707.15,0.0,256.46,ulster
4,6532028,2013,01/08/2013,1082014,10.0,MORTGAGE,3,Low,85000.0,1,...,0,16.78,C,3,15.49,27523.60099,24000.00,0.0,853.04,ulster
5,6316917,2013,01/07/2013,1102014,1.0,RENT,1,Low,82500.0,1,...,0,9.71,B,2,7.96,9901.40164,9000.00,0.0,289.19,munster
6,1570001,2012,01/10/2012,1102015,0.5,RENT,1,Low,55000.0,1,...,0,15.31,C,3,24.34,15040.97044,12000.00,0.0,417.81,Northern-Irl
7,26199528,2014,01/10/2014,1012016,10.0,RENT,1,Low,67980.0,1,...,0,6.03,A,1,6.54,4761.17000,4158.69,0.0,304.36,Northern-Irl
8,35074071,2014,01/11/2014,1122015,10.0,RENT,1,Low,51000.0,1,...,0,8.67,B,2,12.40,2876.52000,2321.36,0.0,221.53,Northern-Irl
9,3725985,2013,01/03/2013,1012016,1.0,MORTGAGE,3,Low,40000.0,1,...,0,16.29,C,3,20.73,14435.85000,8041.99,0.0,437.45,ulster

4. Check the total number of records and distinct loan years.

- *total number of records*

In [48]:
pd.read_sql('select count(*) from loans', conn)

   count(*)
0     70000

- *distinct loan years*

In [49]:
pd.read_sql("select distinct(year) from loans",conn)

   year
0  2013
1  2012
2  2014
3  2010
4  2011
5  2009
6  2008
7  2007

5. List all unique values for key categorical variables like home_ownership, loan_condition, and purpose.

- *Unique value for home_ownership*

In [50]:
pd.read_sql('select distinct(home_ownership) from loans',conn)

  home_ownership
0       MORTGAGE
1           RENT
2            OWN
3          OTHER
4           NONE

- *unique value for loan_condition*

In [51]:
pd.read_sql('select distinct(loan_condition) from loans',conn)

  loan_condition
0      Good Loan
1       Bad Loan

 - *unique value for purpose*

In [52]:
pd.read_sql('select distinct(purpose) from loans',conn)

               purpose
0   debt_consolidation
1     home_improvement
2       major_purchase
3          credit_card
4              medical
5                  car
6                other
7              wedding
8               moving
9       small_business
10               house
11            vacation
12    renewable_energy
13         educational

## B. Transform Phase (Data Cleaning & Feature Engineering)

1. Identify missing or null values in critical columns (loan_amount, interest_rate, annual_inc, loan_condition, purpose).

- *missing values in loan_amount*

In [53]:
pd.read_sql("""
SELECT
    SUM(CASE WHEN loan_amount IS NULL OR loan_amount = '' OR loan_amount = 'nan' THEN 1 ELSE 0 END) AS missing_loan_amount from loans""",conn)

   missing_loan_amount
0                    0

- *missing values in interest_rate*

In [54]:
pd.read_sql('select count(*) from loans where loan_amount is null', conn)

   count(*)
0         0

- *missing values in annual_inc*

In [55]:
pd.read_sql('select count(*) from loans where annual_inc is null', conn)

   count(*)
0         0

- *missing values in loan conition*

In [56]:
pd.read_sql('select count(*) from loans where loan_condition is null', conn)

   count(*)
0         0

- *missing values in loan conition*

In [57]:
pd.read_sql('select count(*) from loans where purpose is null', conn)

   count(*)
0         0

2. Replace missing income values with the median income of all borrowers.

In [58]:
pd.read_sql('select count(*) from loans where annual_inc is null', conn) # no missing values so nothing to replace with.

   count(*)
0         0

3. Standardize categorical values — for example, convert all home_ownership entries to uppercase for consistency.

- *changing home ownership to the upper*

In [59]:
cursor.execute("""
UPDATE loans
SET home_ownership = UPPER(TRIM(home_ownership));
""")
conn.commit()

- changing income category to the upper

In [60]:
cursor.execute("""
UPDATE loans
SET income_category = UPPER(TRIM(income_category));
""")
conn.commit()

- *changing purpose to the upper*

In [61]:
cursor.execute("""
UPDATE loans
SET purpose = UPPER(TRIM(purpose));
""")
conn.commit()

- *changing loan_condition to the upper*

In [62]:
cursor.execute("""
UPDATE loans
SET loan_condition = UPPER(TRIM(loan_condition));
""")
conn.commit()

- *changing region to upper case*

In [63]:
cursor.execute("""
UPDATE loans
SET region = UPPER(TRIM(region));
""")
conn.commit()

4. Create a new column profitability that measures the difference between total_pymnt and loan_amount

In [64]:
# create the column
cursor.execute("""
ALTER TABLE loans
ADD COLUMN profitability REAL;
""")
conn.commit()

In [65]:
# update the columns value
cursor.execute("""
UPDATE loans
SET profitability = total_pymnt - loan_amount;
""")
conn.commit()

In [66]:
#check
pd.read_sql('select total_pymnt,loan_amount,profitability from loans limit 5',conn)

   total_pymnt  loan_amount  profitability
0  11630.35000      10000.0     1630.35000
1  13165.83707      10575.0     2590.83707
2   7849.66000       8875.0    -1025.34000
3   6924.42000      10500.0    -3575.58000
4  27523.60099      24000.0     3523.60099

5. **Create a new column `risk_flag`** based on the loan condition:
- If `loan_condition` = ‘Bad Loan’ → risk_flag = 1
- Else → risk_flag = 0

In [67]:
# create a new column
cursor.execute("""
ALTER TABLE loans
ADD COLUMN risk_flag INTEGER;
""")
conn.commit()

In [68]:
# fill the risk_flag with condition
cursor.execute("""
UPDATE loans
SET risk_flag = CASE WHEN loan_condition = 'BAD LOAN' THEN 1 ELSE 0 END;
""")
conn.commit()

In [69]:
# result
pd.read_sql('select loan_condition, risk_flag from loans limit 5', conn)

  loan_condition  risk_flag
0      GOOD LOAN          0
1      GOOD LOAN          0
2      GOOD LOAN          0
3      GOOD LOAN          0
4      GOOD LOAN          0

In [70]:
df.head()

,id,year,issue_d,final_d,emp_length_int,home_ownership,home_ownership_cat,income_category,annual_inc,income_cat,...,loan_condition_cat,interest_rate,grade,grade_cat,dti,total_pymnt,total_rec_prncp,recoveries,installment,region
0,6297794,2013,01/07/2013,1122015,10.0,MORTGAGE,3,Low,55000,1,...,0,10.64,B,2,20.57,11630.35000,10000.00,0.0,325.69,cannught
1,4526163,2013,01/05/2013,1102014,9.0,RENT,1,Low,60000,1,...,0,21.00,E,5,8.82,13165.83707,10575.00,0.0,398.42,cannught
2,9001808,2013,01/11/2013,1012016,10.0,MORTGAGE,3,Low,63000,1,...,0,13.67,B,2,8.72,7849.66000,6033.91,0.0,301.91,munster
3,7306367,2013,01/09/2013,1122015,10.0,MORTGAGE,3,Low,100000,1,...,0,16.20,C,3,19.52,6924.42000,3707.15,0.0,256.46,ulster
4,6532028,2013,01/08/2013,1082014,10.0,MORTGAGE,3,Low,85000,1,...,0,16.78,C,3,15.49,27523.60099,24000.00,0.0,853.04,ulster

6. Converting issue date to DD/MM/YYYY to YYYY/MM/DD

In [71]:
# create the new column
cursor.execute("""
ALTER TABLE loans
ADD COLUMN issue_date TEXT;
""")
conn.commit()

In [72]:
cursor.execute("""
UPDATE loans
SET issue_date =
        substr(issue_d,7,4) || '-' ||
        substr(issue_d,4,2) || '-' ||
        substr(issue_d,1,2);
""")
conn.commit()

In [73]:
# update the date column
pd.read_sql('select * from loans limit 5',conn)

,id,year,issue_d,final_d,emp_length_int,home_ownership,home_ownership_cat,income_category,annual_inc,income_cat,...,grade_cat,dti,total_pymnt,total_rec_prncp,recoveries,installment,region,profitability,risk_flag,issue_date
0,6297794,2013,01/07/2013,1122015,10.0,MORTGAGE,3,LOW,55000.0,1,...,2,20.57,11630.35000,10000.00,0.0,325.69,CANNUGHT,1630.35000,0,2013-07-01
1,4526163,2013,01/05/2013,1102014,9.0,RENT,1,LOW,60000.0,1,...,5,8.82,13165.83707,10575.00,0.0,398.42,CANNUGHT,2590.83707,0,2013-05-01
2,9001808,2013,01/11/2013,1012016,10.0,MORTGAGE,3,LOW,63000.0,1,...,2,8.72,7849.66000,6033.91,0.0,301.91,MUNSTER,-1025.34000,0,2013-11-01
3,7306367,2013,01/09/2013,1122015,10.0,MORTGAGE,3,LOW,100000.0,1,...,3,19.52,6924.42000,3707.15,0.0,256.46,ULSTER,-3575.58000,0,2013-09-01
4,6532028,2013,01/08/2013,1082014,10.0,MORTGAGE,3,LOW,85000.0,1,...,3,15.49,27523.60099,24000.00,0.0,853.04,ULSTER,3523.60099,0,2013-08-01

7. converting final_d to date format.

In [74]:
# create a column final_date
cursor.execute("""
ALTER TABLE loans
ADD COLUMN final_date TEXT;
""")
conn.commit()

In [75]:
# fill the column final_date
cursor.execute("""
UPDATE loans
SET final_date =
    substr(final_d,4,4) || '-' ||
    substr(final_d,2,2) || '-' ||
    '0' || '' ||
    substr(final_d,1,1);

""")
conn.commit()

## C. Load Preparation Phase (Data Structuring & Export Readiness)

1. Add a default_rate_indicator column that computes the ratio of defaulted loans (Bad Loan) to total loans within the same year.

In [76]:
# Add new column
cursor.execute("""
ALTER TABLE loans
ADD COLUMN default_rate_indicator REAL;
""")
conn.commit()

In [77]:
# Calculating default rate.
cursor.execute("""
UPDATE loans
SET default_rate_indicator = (
    SELECT default_rate
    FROM (
        SELECT year,
               SUM(risk_flag)*1.0/COUNT(*) AS default_rate
        FROM loans
        GROUP BY year
    ) t
    WHERE t.year = loans.year
);
""")
conn.commit()

In [78]:
pd.read_sql('select default_rate_indicator from loans limit 5', conn)

   default_rate_indicator
0                0.138831
1                0.138831
2                0.138831
3                0.138831
4                0.138831

2. Extract loan term as numeric value (e.g., convert ‘36 months’ → 36).

In [79]:
cursor.execute("""
ALTER TABLE loans
ADD COLUMN term_months INTEGER;
""")
conn.commit()

In [80]:
cursor.execute("""
UPDATE loans
SET term_months = CAST(TRIM(REPLACE(term, 'months', '')) AS INTEGER);
""")
conn.commit()

In [81]:
pd.read_sql("""
SELECT term, term_months FROM loans LIMIT 5;
""", conn)

         term  term_months
0   36 months           36
1   36 months           36
2   36 months           36
3   60 months           60
4   36 months           36

3. Add a new column income_to_loan_ratio calculated as the borrower’s annual income divided by the loan amount.

In [82]:
# Add new column
cursor.execute("""
ALTER TABLE loans
ADD COLUMN income_to_loan_ratio REAL;
""")
conn.commit()

In [83]:
# add the ratio calculation
cursor.execute("""
UPDATE loans
SET income_to_loan_ratio =
            CASE WHEN loan_amount > 0 THEN annual_inc * 1.0 / loan_amount
                 ELSE NULL
            END;
""")
conn.commit()

In [84]:
pd.read_sql('select annual_inc, loan_amount,income_to_loan_ratio from loans limit 5', conn)

   annual_inc  loan_amount  income_to_loan_ratio
0     55000.0      10000.0              5.500000
1     60000.0      10575.0              5.673759
2     63000.0       8875.0              7.098592
3    100000.0      10500.0              9.523810
4     85000.0      24000.0              3.541667

4. Create a new table loans_cleaned containing only cleaned and transformed records (no nulls in key fields).

In [85]:
# check and drop if loans cleaned folder is there
cursor.execute("""
DROP TABLE IF EXISTS loans_cleaned;
""")

# Create new loans_cleaned folder with given columns form loans
cursor.execute("""
CREATE TABLE loans_cleaned AS
SELECT
    id,
    year,
    issue_date,
    final_date,
    term_months,
    emp_length_int,
    home_ownership,
    annual_inc,
    loan_amount,
    income_to_loan_ratio,
    purpose,
    interest_rate,
    interest_payments,
    grade,
    dti,
    total_pymnt,
    total_rec_prncp,
    recoveries,
    installment,
    region,
    profitability,
    loan_condition,
    risk_flag,
    default_rate_indicator
FROM loans
WHERE
    loan_amount IS NOT NULL
    AND annual_inc IS NOT NULL
    AND interest_rate IS NOT NULL
    AND purpose IS NOT NULL;
""")
conn.commit()

In [86]:
pd.read_sql('select * from loans_cleaned limit 5', conn)

,id,year,issue_date,final_date,term_months,emp_length_int,home_ownership,annual_inc,loan_amount,income_to_loan_ratio,...,dti,total_pymnt,total_rec_prncp,recoveries,installment,region,profitability,loan_condition,risk_flag,default_rate_indicator
0,6297794,2013,2013-07-01,2015-12-01,36,10.0,MORTGAGE,55000.0,10000.0,5.500000,...,20.57,11630.35000,10000.00,0.0,325.69,CANNUGHT,1630.35000,GOOD LOAN,0,0.138831
1,4526163,2013,2013-05-01,2014-10-01,36,9.0,RENT,60000.0,10575.0,5.673759,...,8.82,13165.83707,10575.00,0.0,398.42,CANNUGHT,2590.83707,GOOD LOAN,0,0.138831
2,9001808,2013,2013-11-01,2016-01-01,36,10.0,MORTGAGE,63000.0,8875.0,7.098592,...,8.72,7849.66000,6033.91,0.0,301.91,MUNSTER,-1025.34000,GOOD LOAN,0,0.138831
3,7306367,2013,2013-09-01,2015-12-01,60,10.0,MORTGAGE,100000.0,10500.0,9.523810,...,19.52,6924.42000,3707.15,0.0,256.46,ULSTER,-3575.58000,GOOD LOAN,0,0.138831
4,6532028,2013,2013-08-01,2014-08-01,36,10.0,MORTGAGE,85000.0,24000.0,3.541667,...,15.49,27523.60099,24000.00,0.0,853.04,ULSTER,3523.60099,GOOD LOAN,0,0.138831

5. 5. **Export the cleaned and enriched dataset (`loans_cleaned`)** from SQL to a `.csv` file for use in Excel (Part II & III).
- Use SQL command (e.g., `COPY TO`, `SELECT INTO OUTFILE`) or database export tools to save as **`loan_cleaned.csv`**.

In [88]:
df = pd.read_sql("SELECT * FROM loans_cleaned;", conn)
df.to_csv("loan_cleaned.csv", index=False)